export default {
  category: [
    {
      categoryId: '1',
      categoryName: 'Salad',
      blackIcon: require('./LhPhotos/saladBlack.png'),
      whiteIcon: require('./LhPhotos/saladWhite.png'),
    },
    {
      categoryId: '2',
      categoryName: 'Burger',
      blackIcon: require('./LhPhotos/burgerBlack.png'),
      whiteIcon: require('./LhPhotos/burgerWhite.png'),
    },
    {
      categoryId: '3',
      categoryName: 'Sandwich',
      blackIcon: require('./LhPhotos/sandwichBlack.png'),
      whiteIcon: require('./LhPhotos/sandwichWhite.png'),
    },
    {
      categoryId: '4',
      categoryName: 'Steak',
      blackIcon: require('./LhPhotos/steakBlack.png'),
      whiteIcon: require('./LhPhotos/steakWhite.png'),
    },
    {
      categoryId: '5',
      categoryName: 'Pasta',
      blackIcon: require('./LhPhotos/pastaBlack.png'),
      whiteIcon: require('./LhPhotos/pastaWhite.png'),
    },
    {
      categoryId: '6',
      categoryName: 'Ice cream',
      blackIcon: require('./LhPhotos/ice-creamBlack.png'),
      whiteIcon: require('./LhPhotos/ice-creamWhite.png'),
    },
    {
      categoryId: '7',
      categoryName: 'Drinks',
      blackIcon: require('./LhPhotos/cocktailBlack.png'),
      whiteIcon: require('./LhPhotos/cocktailWhite.png'),
    },
  ],
  recommended: [
    {
      id: '1',
      categoryId: '1',
      productName: 'Rainbow Salad',
      image: require('./LhPhotos/1.png'),
      description:
        'Build a beautiful, everyday salad that is not only packed with nutrients but tastes amazing too!',
      added: 0,
      price: '30',
      bgcolor: '#E2FBF5',
    },
    {
      id: '26',
      categoryId: '4',
      productName: 'New York Steak',
      image: require('./LhPhotos/26.png'),
      description:
        'Spicy. Grill to perfection, topped with caramelized onion, mushroom, pepper sauce & melted cheese. Served with sauteed veggies & potatoes.',
      added: 0,
      price: '40',
      bgcolor: '#FDFEFE',
    },
    {
      id: '32',
      categoryId: '6',
      productName: 'Cotton Candy Bubblegum',
      image: require('./LhPhotos/32.png'),
      description:
        'A sweet blend of bubblegum-flavored ice cream and cotton candy-flavored ice cream bursting with bubblegum flavored fudge and popping candies.',
      added: 0,
      price: '20',
      bgcolor: '#F3D8F2',
    },
    {
      id: '21',
      categoryId: '4',
      productName: 'Chicken Supreme Steak',
      image: require('./LhPhotos/21.png'),
      description:
        "Chicken breast coated with crumbs deep fried topped with creamy cheese sauce. Served with chef's veggies & choice of potatoes.",
      added: 0,
      price: '40',
      bgcolor: '#FDF2E9',
    },
    {
      id: '25',
      categoryId: '4',
      productName: 'Tarragon Steak',
      image: require('./LhPhotos/25.png'),
      description:
        'Grilled to perfection topped with creamy tarragon sauce. Served with sauteed veggies & choice of potatoes.',
      added: 0,
      price: '40',
      bgcolor: '#F9F5F8',
    },
  ],
  product: [
    {
      id: '1',
      categoryId: '1',
      productName: 'Rainbow Salad',
      image: require('./LhPhotos/1.png'),
      description:
        'Build a beautiful, everyday salad that is not only packed with nutrients but tastes amazing too!',
      added: 0,
      price: '30',
      bgcolor: '#E2FBF5',
    },
    {
      id: '2',
      categoryId: '1',
      productName: 'Shrimp Caesar Salad with Spicy Croutons',
      image: require('./LhPhotos/2.png'),
      description:
        'Shrimp Caesar Salad with Spicy Croutons – a creamy Caesar salad is served with Cajun spiced shrimp and croutons.',
      added: 0,
      price: '35',
      bgcolor: '#EBF7F4',
    },
    {
      id: '3',
      categoryId: '1',
      productName: 'Summer Chopped Salad with Berries',
      image: require('./LhPhotos/3.png'),
      description:
        'Fresh berries are the star of this chopped salad that is topped with a poppy seed dressing and sugared almonds.',
      added: 0,
      price: '30',
      bgcolor: '#EAB3DB',
    },
    {
      id: '4',
      categoryId: '1',
      productName: 'Greek Salad With Chicken',
      image: require('./LhPhotos/4.png'),
      description:
        'Crisp, crunchy, and fresh with tangy Mediterranean flavor, this Greek salad topped with chicken can be meal prepped ahead for weekday lunches or a light and healthy dinner too.',
      added: 0,
      price: '40',
      bgcolor: '#D4EFDF',
    },
    {
      id: '5',
      categoryId: '1',
      productName: 'Chinese Chicken Salad With Sesame Dressing',
      image: require('./LhPhotos/5.png'),
      description:
        'It’s made with crunchy romaine, wontons, and an almond crunch, and is topped with protein-packed chicken breast, pasta noodles, and a flavor-flav sesame dressing.',
      added: 0,
      price: '30',
      bgcolor: '#EAFAF1',
    },
    {
      id: '6',
      categoryId: '1',
      productName: 'Roasted Beet And Ricotta Salad',
      image: require('./LhPhotos/6.png'),
      description:
        '​This roasted beet salad topped with dollops of ricotta cheese sweetened with honey and orange is a fast to make salad that is delicious served chilled, or at room temperature.',
      added: 0,
      price: '35',
      bgcolor: '#FBEEE6',
    },
    {
      id: '7',
      categoryId: '1',
      productName: 'Italian Pasta Salad With Pepperoni',
      image: require('./LhPhotos/7.png'),
      description:
        'salad with pepperoni, veggies, and Italian dressing a potluck favorite everyone will love.',
      added: 0,
      price: '35',
      bgcolor: '#F8F9F9',
    },
    {
      id: '8',
      categoryId: '1',
      productName: 'Garlic Chicken Salad',
      image: require('./LhPhotos/8.png'),
      description:
        'It’s made over a bed of romaine lettuce, extra juicy and flavorful chicken breast, creamy Cesar salad dressing and ALL the veggies your heart desires',
      added: 0,
      price: '40',
      bgcolor: '#FDF2E9',
    },
    {
      id: '9',
      categoryId: '2',
      productName: 'Smash Burgers',
      image: require('./LhPhotos/9.png'),
      description:
        'Smash Burgers are destined to be your favorite burgers! Crispy edges and a juicy middle,housed between two potato buns that soak up the juice, this is the ultimate bite!',
      added: 0,
      price: '40',
      bgcolor: '#F9F5F8',
    },
    {
      id: '10',
      categoryId: '2',
      productName: 'double chicken burger',
      image: require('./LhPhotos/10.png'),
      description:
        'Double crispy fried chicken topped with cheese, mayo, chilli garlic sauce and fresh lettuce with an option of extra cheese add-on',
      added: 0,
      price: '40',
      bgcolor: '#FBFCFC',
    },
    {
      id: '11',
      categoryId: '2',
      productName: 'Double Cheese Burger',
      image: require('./LhPhotos/11.png'),
      description:
        "The most authentic Double Cheese Burger ! 2 smashed beef patties with shredded pickles, caramelised onions, double cheese & Lab’s secret sauce in soft-n-fresh 'Potato Bun' to tantalise your taste buds as you eat.",
      added: 0,
      price: '45',
      bgcolor: '#FDF2E9',
    },
    {
      id: '12',
      categoryId: '2',
      productName: 'Cheese Loaded burger',
      image: require('./LhPhotos/12.png'),
      description:
        'Whole Chicken Breast filled with cheese - onions - jalapenos - iceberg - burger sauce.',
      added: 0,
      price: '45',
      bgcolor: '#FDFEFE',
    },
    {
      id: '13',
      categoryId: '2',
      productName: 'BBQ Flip - Grilled',
      image: require('./LhPhotos/13.png'),
      description:
        "It tastes as good as it looks! Grilled chicken fillet topped with tomatoes, lettuce, caramelised onions, Lab's special smoked and BBQ sauce in soft-n-fresh 'Potato Bun' to enhance the flavour of each bite.",
      added: 0,
      price: '45',
      bgcolor: '#F8F9F9',
    },
    {
      id: '14',
      categoryId: '2',
      productName: 'Zing Melt burger',
      image: require('./LhPhotos/14.png'),
      description:
        'Jumbo crispy chicken - double cheese (mozzarella & american) - iceberg - Mayonnaise',
      added: 0,
      price: '45',
      bgcolor: '#F2F4F4',
    },
    {
      id: '15',
      categoryId: '2',
      productName: 'Premium Chicken Burger',
      image: require('./LhPhotos/15.png'),
      description:
        'Grilled breast fillet on fresh lettuce, tomatoes and grilled onions with steak mayo.',
      added: 0,
      price: '40',
      bgcolor: '#F9EBEA',
    },
    {
      id: '16',
      categoryId: '3',
      productName: 'classic club sandwich',
      image: require('./LhPhotos/16.png'),
      description:
        'Classic Club Sandwich with Grilled Chicken, Turkey Becon, Omelette, Tomatoes, Orange Cheddar Cheese, Cucumbers with honey.',
      added: 0,
      price: '35',
      bgcolor: '#FDFEFE',
    },
    {
      id: '17',
      categoryId: '3',
      productName: 'Chicken Croissant Sandwich',
      image: require('./LhPhotos/17.png'),
      description:
        'Flaky Croissant with Grilled Chicken, Cheddar, Bell Peppers, Chopped Iceberg, Green Chillies and a Honey Mustard Mayo',
      added: 0,
      price: '40',
      bgcolor: '#FDFEFE',
    },
    {
      id: '18',
      categoryId: '3',
      productName: 'The Smoke Salmon Club',
      image: require('./LhPhotos/18.png'),
      description:
        'Norwegian Smoked Salmon Club Sandwich with Hard Boiled Egg, Cucumbers and a Lemon Infused Homemade Mayo served with Fries & Green Salad',
      added: 0,
      price: '40',
      bgcolor: '#FDFEFE',
    },
    {
      id: '19',
      categoryId: '3',
      productName: 'Ranch Chicken Sandwich',
      image: require('./LhPhotos/19.png'),
      description:
        'Delicious grilled chicken thinly sliced, topped with our home-made spicy red sauce served in a cheese and garlic bread, with fries and dip on the side.',
      added: 0,
      price: '35',
      bgcolor: '#FDFEFE',
    },
    {
      id: '20',
      categoryId: '3',
      productName: 'Roasted Beef Sandwich',
      image: require('./LhPhotos/20.png'),
      description:
        'A special treat for beef lovers, thin roasted beef slices topped with our special sauce encased between focaccia bread, served with fries and our home-made dip.',
      added: 0,
      price: '40',
      bgcolor: '#F9EBEA',
    },
    {
      id: '21',
      categoryId: '4',
      productName: 'Chicken Supreme Steak',
      image: require('./LhPhotos/21.png'),
      description:
        "Chicken breast coated with crumbs deep fried topped with creamy cheese sauce. Served with chef's veggies & choice of potatoes.",
      added: 0,
      price: '40',
      bgcolor: '#FDF2E9',
    },
    {
      id: '22',
      categoryId: '4',
      productName: 'Southwestern Steak',
      image: require('./LhPhotos/22.png'),
      description:
        "Char grilled fillet steak, topped with cajun spiced mushroom & onion mixed with cheese. Served with chef's veggies & choice of potatoes.",
      added: 0,
      price: '44',
      bgcolor: '#FDF2E9',
    },
    {
      id: '23',
      categoryId: '4',
      productName: 'Incantare Caesar Chicken Steak',
      image: require('./LhPhotos/23.png'),
      description:
        "Spicy. Char grilled, sauced mushroom, olive & jalapeno pepper with spicy caesar sauce. Served with chef's veggie & choice of potatoes.",
      added: 0,
      price: '45',
      bgcolor: '#FDF2E10',
    },
    {
      id: '24',
      categoryId: '4',
      productName: 'Parmesan Chicken Steak',
      image: require('./LhPhotos/24.png'),
      description:
        'Chicken breasts fried to perfection topped with marinara sauce & parmesan cheese. Served with sauteed veggies, choice of potatoes & hot spaghetti',
      added: 0,
      price: '44',
      bgcolor: '#FDF2E9',
    },
    {
      id: '25',
      categoryId: '4',
      productName: 'Tarragon Steak',
      image: require('./LhPhotos/25.png'),
      description:
        'Grilled to perfection topped with creamy tarragon sauce. Served with sauteed veggies & choice of potatoes.',
      added: 0,
      price: '40',
      bgcolor: '#F9F5F8',
    },
    {
      id: '26',
      categoryId: '4',
      productName: 'New York Steak',
      image: require('./LhPhotos/26.png'),
      description:
        'Spicy. Grill to perfection, topped with caramelized onion, mushroom, pepper sauce & melted cheese. Served with sauteed veggies & potatoes.',
      added: 0,
      price: '40',
      bgcolor: '#FDFEFE',
    },
    {
      id: '27',
      categoryId: '4',
      productName: 'Moroccan Chicken Steak',
      image: require('./LhPhotos/27.png'),
      description:
        'Chicken filled topped with spicy moroccan sauce. Served with sauteed veg and choice of potatoes.',
      added: 0,
      price: '40',
      bgcolor: '#FDFEFE',
    },
    {
      id: '28',
      categoryId: '5',
      productName: 'Penne Arrabiata Pasta',
      image: require('./LhPhotos/28.png'),
      description:
        'Spicy. Penne pasta tossed with hot tomato sauce, mushrooms, black olives & topped with parmesan cheese. Served with garlic bread.',
      added: 0,
      price: '45',
      bgcolor: '#FDFEFE',
    },
    {
      id: '29',
      categoryId: '5',
      productName: 'Chicken Caesar Pasta',
      image: require('./LhPhotos/29.png'),
      description:
        'Penne pasta tossed with spicy creamy sauce, black olives, mushrooms & jalapeno. Served with garlic bread.',
      added: 0,
      price: '45',
      bgcolor: '#FDFEFE',
    },
    {
      id: '30',
      categoryId: '5',
      productName: 'Parmesan Chicken Pasta',
      image: require('./LhPhotos/30.png'),
      description:
        'Golden Fried chicken bread over penne pasta tossed in parmesan cream sauce & topped with marinara & cheese. Served with garlic bread.',
      added: 0,
      price: '45',
      bgcolor: '#FDFEFE',
    },
    {
      id: '31',
      categoryId: '5',
      productName: 'Fettuccine Alfredo Pasta',
      image: require('./LhPhotos/31.png'),
      description:
        'Fettuccine alfredo pasta tossed with alfredo creamy sauce topped with grilled chicken. Served with garlic bread.',
      added: 0,
      price: '45',
      bgcolor: '#FDFEFE',
    },
    {
      id: '32',
      categoryId: '6',
      productName: 'Cotton Candy Bubblegum',
      image: require('./LhPhotos/32.png'),
      description:
        'A sweet blend of bubblegum-flavored ice cream and cotton candy-flavored ice cream bursting with bubblegum flavored fudge and popping candies.',
      added: 0,
      price: '20',
      bgcolor: '#F3D8F2',
    },
    {
      id: '33',
      categoryId: '6',
      productName: 'Chocolate Mousse Royale',
      image: require('./LhPhotos/33.png'),
      description:
        'Chocolate flavored flakes swimming in a bath of rich chocolate mousse flavored ice cream. Dive on in!',
      added: 0,
      price: '20',
      bgcolor: '#F6DDCC',
    },
    {
      id: '34',
      categoryId: '6',
      productName: 'Peanut Butter N Chocolate',
      image: require('./LhPhotos/34.png'),
      description:
        "There's no better gift to your taste buds than chocolate ice cream tied with a chunky peanut butter ribbon.",
      added: 0,
      price: '20',
      bgcolor: '#F6DDCC',
    },
    {
      id: '35',
      categoryId: '6',
      productName: 'Cookies N Cream',
      image: require('./LhPhotos/35.png'),
      description:
        "Dunking your Oreos? A no-brainer. Dunking them in vanilla flavored ice cream? Now that's genius",
      added: 0,
      price: '20',
      bgcolor: '#E3E4DE',
    },
    {
      id: '36',
      categoryId: '6',
      productName: 'Mint Chocolate Chip',
      image: require('./LhPhotos/36.png'),
      description:
        'Chill out. A cool hit of mint flavored ice cream with the joy of chocolate chips throughout.',
      added: 0,
      price: '20',
      bgcolor: '#FDFEFE',
    },
    {
      id: '37',
      categoryId: '6',
      productName: 'Strawberry',
      image: require('./LhPhotos/37.png'),
      description:
        'Delectably delicious strawberry ice cream loaded with real strawberries. Need we say more?',
      added: 0,
      price: '20',
      bgcolor: '#F3D8F2',
    },
    {
      id: '38',
      categoryId: '6',
      productName: 'Pistachio Almond',
      image: require('./LhPhotos/38.png'),
      description:
        'Go nuts with our pistachio flavored ice cream chock-full of roasted almonds.',
      added: 0,
      price: '20',
      bgcolor: '#FDFEFE',
    },
    {
      id: '39',
      categoryId: '6',
      productName: 'Chocolate Chip',
      image: require('./LhPhotos/39.png'),
      description:
        "It's the eternal debate: vanilla or chocolate. But this vanilla flavored ice cream loaded with semi-sweet chocolate chips lets you stay happily undecided.",
      added: 0,
      price: '20',
      bgcolor: '#FDFEFE',
    },
    {
      id: '40',
      categoryId: '7',
      productName: 'Mint lemonade',
      image: require('./LhPhotos/40.png'),
      description:
        'This Limonana (Middle Eastern Frozen Mint Lemonade) is sweet, tart, and refreshing, and perfect for cooling down with on a hot day!',
      added: 0,
      price: '20',
      bgcolor: '#FDFEFE',
    },
    {
      id: '41',
      categoryId: '7',
      productName: 'Pina Colada',
      image: require('./LhPhotos/41.png'),
      description:
        'Made with fresh pineapple, coconut and Greek yogurt, this pina colada smoothie is a fantastic healthy snack or breakfast idea!',
      added: 0,
      price: '25',
      bgcolor: '#FDFEFE',
    },
    {
      id: '42',
      categoryId: '7',
      productName: 'strawberry shake',
      image: require('./LhPhotos/42.png'),
      description:
        'This milkshake is made with strawberry ice cream and fresh strawberries, healthy and yummy!',
      added: 0,
      price: '25',
      bgcolor: '#FDFEFE',
    },
    {
      id: '43',
      categoryId: '7',
      productName: 'blueberry shake',
      image: require('./LhPhotos/43.png'),
      description:
        'This creamy and refreshing blueberry smoothie is made with juice, yogurt, frozen blueberries and banana, all blended together into a frosty drink.',
      added: 0,
      price: '25',
      bgcolor: '#FDFEFE',
    },
    {
      id: '44',
      categoryId: '7',
      productName: 'Vanilla shake',
      image: require('./LhPhotos/44.png'),
      description:
        'This icy classic vanilla shake tastes amazing and will keep you cool .With whipped cream, sugar free chocolate syrup.',
      added: 0,
      price: '25',
      bgcolor: '#FDFEFE',
    },
  ],
};
